#!/bin/bash
export PATH="/usr/local/sbin:$PATH"

for CONFIG_FILE in `find $HOME/.dotfiles -name "config.sh" -print`
do
    [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
done

[ -f $HOME/.bashrc ] && source $HOME/.bashrc
