#!/bin/sh

compaudit | xargs chmod g-w

ZSH_PLUGINS_DIR="$HOME/.config/zsh/plugins"

if [ ! -d $ZSH_PLUGINS_DIR ]; then
    mkdir -p $ZSH_PLUGINS_DIR
fi

# zsh-git-prompt
git clone https://github.com/zsh-git-prompt/zsh-git-prompt.git --depth 1 $ZSH_PLUGINS_DIR/zsh-git-prompt

# zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions --depth 1 $ZSH_PLUGINS_DIR/zsh-autosuggestions

# fast-syntax-highlighting
git clone https://github.com/zdharma/fast-syntax-highlighting --depth 1 $ZSH_PLUGINS_DIR/fast-syntax-highlighting

# zsh-completions
git clone https://github.com/zsh-users/zsh-completions.git --depth 1 $ZSH_PLUGINS_DIR/zsh-completions
