#!/bin/bash
export PATH="/usr/local/sbin:$PATH"

export DOTFILES_DIR="$HOME/.dotfiles"
source "$DOTFILES_DIR/utils/variables.sh"

[ -f /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion

for CONFIG_FILE in `find $HOME/.dotfiles/config -name "*.sh" -print`
do
    [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
done

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi
